import TEXTS from '../texts/texts';
import {
  DiagServiceIcon,
  EngineServiceIcon,
  WheelServiceIcon,
  OilServiceIcon,
  BodyServiceIcon,
  BatteryServiceIcon,
  IncurServiceIcon,
  CustomServiceIcon,
} from '../../assets/icons';
import diagServiceImg from '../../assets/images/auto-diagnostic.jpg';

const SERVICES = [
  {
    id: 1,
    text: `${TEXTS.services.diag}`,
    logo: <DiagServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 2,
    text: `${TEXTS.services.engine}`,
    logo: <EngineServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 3,
    text: `${TEXTS.services.wheel}`,
    logo: <WheelServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 4,
    text: `${TEXTS.services.oil}`,
    logo: <OilServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 5,
    text: `${TEXTS.services.body}`,
    logo: <BodyServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 6,
    text: `${TEXTS.services.batteries}`,
    logo: <BatteryServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 7,
    text: `${TEXTS.services.insur}`,
    logo: <IncurServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 8,
    text: `${TEXTS.services.custom}`,
    logo: <CustomServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 9,
    text: `${TEXTS.services.wash}`,
    logo: <DiagServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
  {
    id: 10,
    text: `${TEXTS.services.ac}`,
    logo: <EngineServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
    img: {
      image: diagServiceImg,
      alt: 'auto-diagnostic.jpg',
    },
  },
];

export default SERVICES;
